### PR TITLE
Adding composer.json. Fixes #1.

### LINKED ISSUE #1: Add composer.json
Lacking it makes this more difficult to use in most modern PHP projects!

### PR DESCRIPTION
**Pull request by aendra-rininsland**

### CODE REVIEW

**Comment by aendra-rininsland** [comment]
N.b., you should probably also tag a release in order to make this work.

**Comment by brandfocus** [comment]
+1

**Comment by chrisbarr** [comment]
+1

**Comment by chrisbarr** [comment]
Should also add an `autoload` property, eg.

```
    "autoload": {
        "files": ["what3words.class.php"]
    }
```

**Comment by vicchi** [comment]
@aendrew Thanks for this - I'll get this merged (and version tagged) this morning

**Comment by vicchi** [comment]
Manually merged; see commit 2d3ccaad4848a5449404ef896da795ce55ed8131

**Comment by aendra-rininsland** [comment]
Woo! Thanks! :+1:

**Pull request closed without merging**
